spring:
  datasource:
    url: jdbc:mysql://localhost:33306/dev_database?rewriteBatchedStatements=true&profileSQL=true&logger=Slf4JLogger&maxQuerySizeToLog=999999
    username: dev_user
    password: dev_password
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none # Hibernate가 DDL 실행하지 않음
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        jdbc.time_zone: Asia/Seoul
        connection.characterEncoding: UTF-8
        connection.useUnicode: true
        connection.collation: utf8mb4_unicode_ci
        format_sql: true  # SQL 보기 좋게 출력
  data:
    redis:
      host: localhost
      port: 6379
  cache:
    type: redis


logging:
  level:
    org.hibernate.sql: DEBUG                   # SQL 쿼리 로깅
    org.hibernate.orm.jdbc.bind: TRACE         # SQL 바인딩 파라미터 로깅
    org.hibernate.type.descriptor.sql: TRACE   # SQL 파라미터 값 로깅
    org.springframework.transaction.interceptor: DEBUG  # 트랜잭션 정보

# Actuator 설정
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus   # 웹으로 노출할 엔드포인트
  endpoint:
    metrics:
      access: read-only        # none | read-only | unrestricted
    prometheus:
      access: read-only
# 선택: Actuator만 별도 포트로 할 경우
#  server:
#    port: 9091