
services:
  mysql:
    image: mysql:8.0
    container_name: mysql-container-movie
    restart: always
    ports:
      - "3306:3306"  # 호스트의 3306 포트와 컨테이너의 3306 포트 연결
    environment:
      MYSQL_ROOT_PASSWORD: root_password   # MySQL root 계정 비밀번호
      MYSQL_DATABASE: dev_database         # 생성할 데이터베이스 이름
      MYSQL_USER: dev_user                 # 사용자 계정 이름
      MYSQL_PASSWORD: dev_password         # 사용자 계정 비밀번호
      TZ: Asia/Seoul                       # 시간대 설정 (KST로 설정)
    volumes:
      - mysql_data:/var/lib/mysql          # 데이터 영구 저장 (볼륨 사용)
    command:
      - --character-set-server=utf8mb4         # 인코딩 규칙 (유니코드 4바이트 지원)
      - --collation-server=utf8mb4_0900_ai_ci  # 정렬 규칙 (대소문자 및 액센트 구분 없음)

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - "./monitoring/prometheus.yaml:/etc/prometheus/prometheus.yml"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "13000:3000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped

volumes:
  mysql_data: